### ISSUE TITLE
Does Podsnatch re-download deleted podcast episodes?

### ISSUE THREAD

**Issue by WolfgangDpunkt** [robotmlg/podsnatch#5]
That sounds very promising.
Does this tool re-download deleted podcast episodes?

Before I try it myself, I'll just ask, possibly as a suggestion to add this info in the readme ;-)

For me, this is the most important feature, because I remove episodes after finished listening to it, and it would be fatal if they are then downloaded again.
Thank you very much!

**Comment by robotmlg** [comment]
Yes, podsnatch will redownload deleted episodes.  The tool is designed for building an archive, and not for everyday listening.  Thank you for your interest, but this is not the tool for your needs, and I do not plan to add this feature.

**Comment by WolfgangDpunkt** [comment]
Thank you for the quick reply and the comprehensible clarification!
